name: facebook/contriever
revision: 2bd46a25019aeea091fd42d1f0fd4801675cf699
query_prefix: ""
document_prefix: ""
pooling: mean
expected_dimension: 768
batch_size: 32
max_length: 512
normalize: true
dropout_scope: all
dropout_probability: null
