name: sentence-transformers/gtr-t5-base
revision: 9801579ce813fb37541e6098dffd17959fffcd6e
query_prefix: ""
document_prefix: ""
pooling: mean
expected_dimension: 768
batch_size: 32
max_length: 512
normalize: true
dropout_scope: all
dropout_probability: null
